import Link from "next/link";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import {
  Activity, ArrowRight, Award, BarChart3, Brain, CheckCircle2,
  Dna, FlaskConical, Hospital, Microscope, Shield, Users,
} from "lucide-react";

const FEATURES = [
  { icon: Dna,         title: "Multi-class Subtype ML",    desc: "Predicts Adenocarcinoma, Squamous Cell, SCLC, and more using supervised ML on clinical data." },
  { icon: Brain,       title: "Gemini AI Explanations",    desc: "Each prediction is paired with a structured clinical interpretation generated by Google Gemini." },
  { icon: BarChart3,   title: "Analytics Dashboard",       desc: "Subtype distribution, risk trends, model comparison charts, and feature importance visualisation." },
  { icon: FlaskConical,title: "Genomic Markers",           desc: "Incorporates EGFR, KRAS, ALK mutations and PD-L1 / TMB biomarkers for precision oncology context." },
  { icon: Microscope,  title: "12 Clinical Features",      desc: "Uses only clinically obtainable tabular data — no CT scans, no imaging pipelines required." },
  { icon: Shield,      title: "JWT-Secured Doctor Portal", desc: "bcrypt-hashed passwords, JWT tokens, and doctor-scoped data access throughout the system." },
];

const SUBTYPES = [
  { label: "No Cancer",     color: "bg-green-500",  desc: "Benign assessment — monitoring recommended." },
  { label: "Adenocarcinoma",color: "bg-blue-500",   desc: "Most common NSCLC; EGFR/ALK-driven; targeted therapy available." },
  { label: "Squamous Cell", color: "bg-amber-500",  desc: "Central NSCLC; linked to smoking; immunotherapy eligible." },
  { label: "SCLC",          color: "bg-red-500",    desc: "Small cell; rapidly progressive; combination chemotherapy." },
];

export default function LandingPage() {
  return (
    <div className="page-wrapper">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-br from-primary-50 via-white to-teal-50 dark:from-dark-bg dark:via-dark-card dark:to-dark-bg border-b border-medical-border dark:border-dark-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary-100 dark:bg-primary-900/30 border border-primary-200 dark:border-primary-800 text-primary-700 dark:text-primary-400 text-xs font-semibold mb-6">
              <Activity className="w-3.5 h-3.5" />
              Multi-class Lung Cancer Subtype Prediction · v2.0
            </div>
            <h1 className="font-display font-black text-5xl sm:text-6xl lg:text-7xl text-medical-text dark:text-dark-text leading-tight">
              PulmoScan <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-600 to-teal-500">AI</span>
            </h1>
            <p className="mt-6 text-xl text-medical-muted dark:text-dark-muted leading-relaxed max-w-2xl">
              A supervised machine learning clinical decision support system that predicts
              lung cancer subtypes — Adenocarcinoma, Squamous Cell, SCLC and more —
              from tabular clinical and genomic features.
            </p>
            <div className="flex flex-wrap gap-4 mt-10">
              <Link href="/auth/login"    className="btn-primary flex items-center gap-2 text-base">
                Get Started <ArrowRight className="w-4 h-4" />
              </Link>
              <Link href="/auth/register" className="btn-outline flex items-center gap-2 text-base">
                Create Account
              </Link>
            </div>
            <div className="flex flex-wrap gap-6 mt-10 text-sm text-medical-muted dark:text-dark-muted">
              {["5+ ML Algorithms", "12 Clinical Features", "Gemini AI Explanations", "Batch CSV Upload"].map(t => (
                <div key={t} className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-green-500" /> {t}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Decorative blobs */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-br from-primary-200/40 to-teal-200/40 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none" />
        <div className="absolute bottom-0 left-1/2 w-64 h-64 bg-gradient-to-br from-teal-200/30 to-cyan-200/30 rounded-full blur-3xl pointer-events-none" />
      </section>

      {/* Subtypes */}
      <section className="py-16 bg-white dark:bg-dark-card border-b border-medical-border dark:border-dark-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="font-display font-black text-3xl text-medical-text dark:text-dark-text">Predicted Cancer Subtypes</h2>
            <p className="text-medical-muted dark:text-dark-muted mt-2">ML-driven classification across four primary lung cancer subtypes.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {SUBTYPES.map(({ label, color, desc }) => (
              <div key={label} className="card p-6 text-center hover:shadow-medical transition-shadow">
                <div className={`w-12 h-12 rounded-2xl ${color} mx-auto mb-4 flex items-center justify-center`}>
                  <Dna className="w-6 h-6 text-white" />
                </div>
                <h3 className="font-display font-bold text-medical-text dark:text-dark-text mb-2">{label}</h3>
                <p className="text-sm text-medical-muted dark:text-dark-muted">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-16 bg-[var(--color-bg)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="font-display font-black text-3xl text-medical-text dark:text-dark-text">System Features</h2>
            <p className="text-medical-muted dark:text-dark-muted mt-2">Everything a clinician needs in one integrated platform.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map(({ icon: Icon, title, desc }) => (
              <div key={title} className="card p-6 hover:shadow-medical transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-100 to-teal-100 dark:from-primary-900/30 dark:to-teal-900/30 flex items-center justify-center mb-4">
                  <Icon className="w-5 h-5 text-primary-600 dark:text-primary-400" />
                </div>
                <h3 className="font-display font-bold text-medical-text dark:text-dark-text mb-2">{title}</h3>
                <p className="text-sm text-medical-muted dark:text-dark-muted leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats strip */}
      <section className="py-12 bg-gradient-to-r from-primary-600 to-teal-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center text-white">
            {[
              { icon: Dna,      value: "4+",    label: "Cancer Subtypes"    },
              { icon: Activity, value: "5+",    label: "ML Algorithms"      },
              { icon: Users,    value: "12",    label: "Clinical Features"  },
              { icon: Award,    value: "95%+",  label: "Target Accuracy"    },
            ].map(({ icon: Icon, value, label }) => (
              <div key={label} className="flex flex-col items-center gap-2">
                <Icon className="w-8 h-8 text-white/70" />
                <div className="text-4xl font-display font-black">{value}</div>
                <div className="text-white/70 text-sm">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CHUB reference */}
      <section className="py-16 bg-white dark:bg-dark-card border-t border-medical-border dark:border-dark-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col lg:flex-row gap-8 items-center">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-slate-700 to-slate-800 flex items-center justify-center shrink-0">
            <Hospital className="w-8 h-8 text-white" />
          </div>
          <div className="flex-1">
            <h2 className="font-display font-bold text-2xl text-medical-text dark:text-dark-text mb-2">
              Developed for Clinical Contexts like CHUB Butare, Rwanda
            </h2>
            <p className="text-medical-muted dark:text-dark-muted leading-relaxed">
              PulmoScan AI was designed as a capstone clinical decision support prototype for resource-conscious
              healthcare settings. CHUB (Centre Hospitalier Universitaire de Butare) confirmed 135 lung cancer
              cases between 2022–2025, with 2023 as the peak year. The system helps clinicians prioritise
              specialist referrals and treatment planning.
            </p>
          </div>
          <Link href="/auth/register" className="btn-primary shrink-0 flex items-center gap-2">
            Start Using PulmoScan <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      {/* Disclaimer */}
      <section className="py-8 bg-amber-50 dark:bg-amber-900/20 border-t border-amber-200 dark:border-amber-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-sm text-amber-700 dark:text-amber-400">
            <strong>Medical Disclaimer:</strong> PulmoScan AI is a clinical decision-support tool developed for
            educational purposes. It does <strong>not</strong> constitute a formal medical diagnosis.
            All predictions must be reviewed by a qualified healthcare professional before clinical action.
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
